apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  labels:
    app: attempt1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attempt1
  template:
    metadata:
      labels:
        app: attempt1
    spec:
      containers:
      - name: myproj
        image: namandocker101/attempt1
        ports:
        - containerPort: 80
